project:
  type: website
  output-dir: docs

website:
  title: "websitetest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/jtrnyc
      - icon: github
        menu:
          - text: View Source
            url:  https://www.github.com/jtr13/websitetest
          - text: Issues
            url:  https://www.github.com/jtr13/websitetest

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

