project:
  type: website
  
website:
  title: "websitetest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/jtrnyc
      - icon: github
        menu:
          - text: View Source
            url:  https://github.com/jtr13/websitetest
          - text: Open an issue
            url:  https://github.com/jtr13/websitetest/issues/new

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

